# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:15
    container_name: trello2.0
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trello2.0
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
